# The World address to index.
world_address = "0x04cd49c7a8c4e2f44cee045b3984d13e5fbffd1e54b294fb495e7830c976aa49"
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true

[sql]
historical = ["tamagotchi-TrophyProgression"] 