# The World address to index.
world_address = "0x056b054364e71b68da48b4cb25fde8969b5cacd948ba3caaf44e9093fc74f081"
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

# Indexing Options
[indexing]
transactions = true
pending = true

[sql] 
historical = ["tamagotchi-TrophyProgression"] 