# The World address to index.
world_address = "0x010e0d672ba1d2e7c6f163f2c8f9b97a9e1b2bb6720652ab346c4cd44f370dea"
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[sql]
historical = ["tamagotchi-TrophyProgression"] 