# The World address to index.
world_address = "0x056b054364e71b68da48b4cb25fde8969b5cacd948ba3caaf44e9093fc74f081"
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true

[sql]
historical = ["tamagotchi-TrophyProgression"] 